Add throwable capture balls
feldoh/PawnStorages pull request #41
Opened 2024-07-01 18:34 UTC by keyz182

- Throw to capture
  - if non-friendly and downed, pawn is captured as prisoner
  - if non-friendly and not downed, nothing happens
  - if friendly, pawn is stored normally
-  Throw to release
   - Releases the pawn at the position hit

2024-07-01 18:37 UTC, keyz182 commented
Implemented separately from the crystal for now - if you want I can merge them into one.

2024-07-06 17:15 UTC, feldoh requested changes

2024-07-06 19:07 UTC, keyz182 commented on 1.5/Defs/ThingDefs_Items/Items_Exotic.xml
> +                <destroyOnZeroCharges>true</destroyOnZeroCharges>
Yup, that's right. That said, I don't think this is having any effect anymore, as I'm not manually destoying the ball from the projectile on capture start. Might need to revisit that behaviour as it essentially lets you keep throwing until you capture.

2024-07-06 19:08 UTC, keyz182 commented on 1.5/Source/PawnStorages/PawnStorages/CompPawnStorage.cs
> +    public void TransferPawn(CompPawnStorage otherStore, Pawn pawn)
What do you mean by base comp here? I thought CompPawnStorage was the base comp.

2024-07-06 19:09 UTC, keyz182 commented on 1.5/Source/PawnStorages/PawnStorages/CompPawnStorage.cs
> +            if (Props.MaxStoredPawns == 1)
Might have missed something, but I thought all the label code was here in this function?

2024-07-06 19:12 UTC, feldoh commented on 1.5/Source/PawnStorages/PawnStorages/CompPawnStorage.cs
> +            if (Props.MaxStoredPawns == 1)
🤦 I thought this was a special one for absolutely no reason

2024-07-06 19:12 UTC, feldoh commented on 1.5/Source/PawnStorages/PawnStorages/CompPawnStorage.cs
> +    public void TransferPawn(CompPawnStorage otherStore, Pawn pawn)
🤦 I thought this was a special one for absolutely no reason

2024-07-06 19:52 UTC, feldoh approved these changes

2024-07-06 19:52 UTC, merged